language: node_js
node_js:
  - "stable"
script:
  - npm run build
  # - npm test
  # - npm run test:coverage
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master